Draft: Oifs48r1 standalone
esm-tools/esm_tools pull request #1091
Opened 2023-11-07 10:22 UTC by JanStreffing

Compiles and runs a standalone OpenIFS 48r1 simulation. Caveats: For me! On levante! It's not beautiful.. Feedback on style welcome.

2023-11-07 12:53 UTC, joakimkjellsson commented
Nice work! I think this will be a good guide for installing on other platforms, e.g. HLRN etc. 
One question: Is there a reason you use GNU and OpenMPI, and not Intel? Since we compile XIOS, NEMO etc with Intel it would be preferrable to know we can run 48r1 also with Intel.

2023-11-07 12:54 UTC, joakimkjellsson approved these changes
Very nice work! I have no immediate plans to use this on HLRN soon, but it seems pretty straightforward to follow @JanStreffing work.

2023-11-07 13:01 UTC, JanStreffing commented
Intel did not work on either juwels or gnu. It compiles but runtime crashes with some library relinking error. Nothing fundamental I think. I ended up copying the environments from DestinE project where the use GNU. They also have the same error when they try intel. 

I agree, life will be easier once gnu works.

I tried to clean up a bit. Right now, I am replacing the juwels compiler_mpi for all versions. That's not good. I want to do that only for 48r1. I tried:

```
choose_version:
        48r1:
                mip: none
                o3_scheme: none
                cloudfixer: none
                massfixer: 3
                tl_o3_data_dir: "${pool_dir}/../climate.v020/"
                add_namelist_changes:
                        fort.4:
                                NAMRES:
                                        NFRRES: ${nfrres}
                                        NRESTS${nrest_ind}: ${nfrests}
                                NAMPAR0:
                                        NPROC: ${oifs.nproc}
                                NAMRIP:
                                        TSTEP: ${oifs.time_step}
                                        CSTOP: "t${oifs.next_step}"
                                NAMARG:
                                        CNMEXP: "${oifs.input_expid}"
                                NAMPPC:
                                        LRSACC: ".true." # reset accumulation of fluxes
                environment_changes:
                        add_export_vars:
                                OIFS_CYCLE: 48r1
                                OIFS_HOME: ${model_dir}
                                OIFS_LOGFILE: "$OIFS_HOME/oifs_test_log.txt"
                                OIFS_DATA_DIR: /work/ab0246/a270092/input/oifs-48r1/
                                DATA: "${general.work_dir}"
                                LD_LIBRARY_PATH: '$LD_LIBRARY_PATH:${model_dir}/build/lib'
                                GRIB_SAMPLES_PATH: '${model_dir}/build/share/eccodes/ifs_samples/grib1_mlgrib2'
                        # TODO: This can go into further reading oifs48.env.yaml, as soon as further reading works for esm_master
                        choose_computer.name:
                                juwels:
                                        compiler_mpi: gnu2023_ompi2023
                                        add_export_vars:
                                                OIFS_DATA_DIR: "/p/project/chhb19/streffing1/input/oifs-48r1/"
                                levante:
                                        compiler_mpi: gnu11_ompi2022
                                        iolibraries: system_gnu_libs
                                        add_export_vars:
                                                OIFS_DATA_DIR: "/work/ab0246/a270092/input/oifs-48r1/"
```

But I just get the default from levante.yaml. Another case of early resolve issue?

2023-11-07 14:12 UTC, JanStreffing commented
the latest commit https://github.com/esm-tools/esm_tools/pull/1091/commits/0e47c090958676ec84e5e46f003f5b0dc92b9a57 break the selection of iolibraries: system_gnu_libs for levante. We need to get some form of this to work, because it's not okay to just change the iolibraries variable for all oifs versions.

2023-11-07 15:18 UTC, JanStreffing commented on configs/components/oifs/oifs.yaml
> +perturb: 0
I changed the default behavior here, not by accident. I think we want testability and reproducibility from the standalone case. Perturbation experiments can be made, but are not the default.

2023-11-07 15:50 UTC, JanStreffing commented
Changes reported by CI tests look ok to me. Ready for review

2023-11-07 16:10 UTC, JanStreffing commented
Strange, I though we already solved the issue of further_reading not being evaluated by adding it to the early vars. In fact I'm positive I ran a test with that. Yet now I get the same behaviour again of not oifs48.env.yaml evaluation..

2023-11-07 16:13 UTC, JanStreffing commented
I added major_version as another early var, but that did not help either.

2023-11-07 16:39 UTC, nwieters commented
Hi @JanStreffing,
adding further_reading to early_choose_vars  is not enough. Miguel and I just had a look together. I think we are close to attach the right file. I will continue on this tomorrow.

2023-11-10 15:06 UTC, mandresm commented
I merge the polished fix for the further_reading that passed all the tests.

2023-12-05 08:40 UTC, JanStreffing commented
@mandresm:
can you check what the runtime differences are for https://github.com/esm-tools/esm_tools/actions/runs/6826452745/job/18566413063?pr=1091 ?
Do they look ok, or is there something that needs to be changed still?

2023-12-13 18:01 UTC, mandresm requested changes
Hi @JanStreffing,

Nice PR! The append_daily_icml_file is doing quite some nice magic. I think we hitted this wall once in DestinE, I guess you know about that. I hope this is now solved there too.

Other than that just some suggestions. I'll be adding a test for standalone OpenIFS-48r1 tomorrow.

2023-12-13 18:01 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +    # If 1, use Coddington spectrum which reduced stratospheric warm bias
```suggestion
# If 1, use Coddington spectrum which reduced stratospheric warm bias
```

2023-12-13 18:01 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +    # If 1, use Coddington spectrum which reduced stratospheric warm bias
just to minimize changes :)

2023-12-13 18:01 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +                                        compiler_mpi: gnu2023_ompi2023
This information is repeated in `oifs48.env.yaml` isn't it? In that case we should get rid of it from here, if it doesn't do any harm.

2023-12-13 18:01 UTC, mandresm commented on configs/machines/levante.yaml
> +                #netcdf_cxx_root: /sw/spack-levante/netcdf-cxx-4.2-q3vhdk #JS: copied from intel2022_impi2021; does this do anything?
This is used in `fesom.yaml` (FESOM-1.4) to set the NETCDF_CXX variables, for example:
```bash
NETCDF_DIR: ${computer.netcdf_cxx_root}
```
I don't think you need this, if we ever need it for AWICM-1, I'll write it here again. For now you can remove it.

2023-12-13 18:01 UTC, mandresm commented on src/esm_parser/esm_parser.py
> +early_choose_vars = ["include_models", "version", "major_version", "omp_num_threads", "environment_changes", "further_reading"]
`major_version` is not needed. The fix I made should find any of the variables listed here, no matter where they are nested because I added recursion to the function. Same goes for `environment_changes`.

2023-12-13 18:01 UTC, mandresm commented on configs/components/oifs/link_icmcl_file.sh
> +ln -s ${icmcl_file} ${outdir}/ICMCL${outexpid}INIT
I have the impression this whole function could be deleted and substituted for 3-4 lines in the yaml. Do you think that would make sense @JanStreffing?

2023-12-13 18:02 UTC, mandresm commented
I'm having an issue during compilation:
```
[ 18%] Linking C shared library ../../lib/libeccodes.so
[ 18%] Built target eccodes
make: *** [Makefile:166: all] Error 2
ERROR: Command /work/ab0246/a270152/model_codes/oifs-48r1/build/build.sh --without-configure failed in directory                                                                                                   
/work/ab0246/a270152/model_codes/oifs-48r1

Time elapsed for failed build: 00:00:12
```

2023-12-13 19:10 UTC, JanStreffing commented on configs/components/oifs/oifs.yaml
> +                                        compiler_mpi: gnu2023_ompi2023
correct, that was a leftover from before the further reading fix.

2023-12-13 19:13 UTC, JanStreffing commented on configs/machines/levante.yaml
> +                #netcdf_cxx_root: /sw/spack-levante/netcdf-cxx-4.2-q3vhdk #JS: copied from intel2022_impi2021; does this do anything?
i removed it and the commit message links to your comment here, in case anyone ever needs to know why.

2023-12-13 19:18 UTC, JanStreffing commented on src/esm_parser/esm_parser.py
> +early_choose_vars = ["include_models", "version", "major_version", "omp_num_threads", "environment_changes", "further_reading"]
removed, and commit links to your message for explaination.

2023-12-13 19:20 UTC, JanStreffing commented on configs/components/oifs/link_icmcl_file.sh
> +ln -s ${icmcl_file} ${outdir}/ICMCL${outexpid}INIT
The purpose is to like files at a somewhat unusual time in the workflow, if I remember correctly. Maybe it can be replaced... Do you want to try? ;-)

2023-12-13 19:34 UTC, JanStreffing commented
> I'm having an issue during compilation:
> 
> ```
> [ 18%] Linking C shared library ../../lib/libeccodes.so
> [ 18%] Built target eccodes
> make: *** [Makefile:166: all] Error 2
> ERROR: Command /work/ab0246/a270152/model_codes/oifs-48r1/build/build.sh --without-configure failed in directory                                                                                                   
> /work/ab0246/a270152/model_codes/oifs-48r1
> 
> Time elapsed for failed build: 00:00:12
> ```
Not an error I remember seeing. We did a good job on making sure no one can access OpenIFS code. So I can't look into your folder at your logfiles. :)

2023-12-18 08:30 UTC, mandresm commented on configs/components/oifs/link_icmcl_file.sh
> +ln -s ${icmcl_file} ${outdir}/ICMCL${outexpid}INIT
You're right, the files are copied/moved/linked before the preprocessing takes place and the ICMCL files is created. So you need something at this point. We should offer you a better way of doing this from ESM-Tools directly... but let's be practical about it and use this until we have a better solution in the future.

2023-12-18 14:37 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +                                        NRESTS${:}: -1 ${nfrests}
I don't think this syntax could possibly work. What do you want to do exactly? At the moment is trying to find a variable named `:`

2024-01-15 09:34 UTC, mandresm commented
#approve-changes

2024-01-15 09:34 UTC, mandresm approved these changes

2024-01-15 09:43 UTC, mandresm commented
#bump

2024-01-15 09:50 UTC, mandresm commented
#bump #minor

2024-01-18 17:28 UTC, mandresm commented
#bump #minor

2024-01-18 17:29 UTC, merged