Merge latest developments from GEOMAR into release
esm-tools/esm_tools pull request #1138
Opened 2024-02-19 10:25 UTC by seb-wahl

Hi
this will merge mostly FOCIOIFS related developments. 
Still contains the bug described by @joakimkjellsson in #1137

2024-02-19 10:28 UTC, seb-wahl commented
It also solves #1133

2024-07-19 14:54 UTC, pgierz commented
Merge conflicts resolved, but it looks like @joakimkjellsson is still working on this branch (recent commits in the last few days). 

I also would like one of the other main esm-tools devs to look over this, but looking at it (only briefly) I do not see any big concerns.

@seb-wahl: it would be nice if we could get a demo of the monitoring feature, I just saw the file name "notebook" somewhere while browsing, and it might be interesting for our scientists as well.

Have a nice summer holiday!

2024-07-19 15:02 UTC, joakimkjellsson commented
Hi @pgierz and @seb-wahl 

Yes I've been doing a few patches on `geomar_dev` to make the models run on our new machines. 

If needed, I can pause for a while to make the merging easier. 

Cheers
Joakim

2024-07-19 15:05 UTC, pgierz commented
Hey @joakimkjellsson,

No problem, keep hacking away ;-)
I'll occasionally merge release into this one, so you might want to a `git pull` once in a while.

MfG PG

2024-07-19 15:17 UTC, joakimkjellsson commented
Unfortunately, something must have gone wrong during the merge. I did `git pull` just now and nothing works. 
For example
```bash
(base) [smomw352@nesh-login1 models_oneapi]$ esm_master comp-focioifs-agrif-4.0 -c
(base) [smomw352@nesh-login1 models_oneapi]$
```
i.e. `esm_master` does not do anything. No error but no result. 

Any ideas? Any big changes that happened? 

/Joakim

2024-07-22 06:38 UTC, pgierz commented
Hmm, that's odd...sorry about that, I'll have a look once I'm in the office. For now you can just revert the merge so you can keep working. For that, you can do something like this:

```
$ git rebase -i HEAD^^ # Set's your git back by two commits, and opens up the commits in an editor
... edit away the merge commit
... close editor
$ git commit -m "removes merge"
$ git push     
```

I'm not 100% sure, and the internet is dropping in and out on my train, but that should put you back into a workable state.

2025-02-14 12:30 UTC, mandresm requested changes
It all looks great and not problematic. The changes in the `src` need though to be tested more extensively. Consequently, what I will do will be to create a new branch from this one, and merge almost everything but the changes in `src`. The changes in `src` can be then tested more throughly in this PR.

2025-02-14 12:30 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +                        ICMGG: ICMGG
@JanStreffing, are you okay with this change? Otherwise, this can be moved to `oifs.add_outdata_files` in the `focioifs.yaml`

2025-02-14 12:30 UTC, mandresm commented on configs/components/oifs/oifs.env.yaml
> +        - "LAPACK_LIB='-qmkl=sequential'"
@seb-wahl, can you explain why this flag needs the extra `q`? I'm curious to understand why is it now needed in HLRN.

2025-02-14 12:30 UTC, mandresm commented on configs/components/oifs/oifs_grib_output_to_restart_new.sh
> +echo " ==== Can you feel that? We are done here... "
XDDDD <3

2025-02-14 12:30 UTC, mandresm commented on configs/components/oasis3mct/oasis3mct.yaml
> -mct_version: "2.8" # TODO: set mct_version = version (can't do at the moment as version is a string)
does this change affect AWIESM2/AWICM3?

2025-02-14 12:30 UTC, mandresm commented on configs/components/oifs/oifs.env.yaml
> +      add_module_actions:
```suggestion
      add_module_actions:
```

2025-02-14 12:30 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +                #time_step: 3600
```suggestion
```

2025-02-14 12:30 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +                        ICMGG: ICMGG
I don't think this will be a problem, if the files are not found they should be ignored.

2025-02-14 12:30 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +ini_pseudo_initial_date: "${initial_date}" #${prev_run.general.start_date}"
I don't think this can go in. It will break things pretty hard, but I still need to check lines below

2025-02-14 12:30 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +# start_date for the new run to be 1850 and also trick OpenIFS to think initial_date is 1849.
Amazing comment, thank you so much @joakimkjellsson!!!

2025-02-14 12:30 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +ini_pseudo_initial_date: "${initial_date}" #${prev_run.general.start_date}"
Indeed, this can go in :) Now I get it

2025-02-14 12:30 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +                #                branchoff: true
```suggestion
```

2025-02-14 12:30 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +#                type: shell
```suggestion
```

2025-02-14 12:30 UTC, mandresm commented on configs/machines/all_machines.yaml
> +
```suggestion
```

2025-02-14 12:30 UTC, mandresm commented on src/esm_environment/esm_environment.py
> +                f'#!{self.config.get("sh_interpreter", "/bin/bash")}\n'
I cannot recall well why, but this breaks stuff in other machines. Suggest to remove it from here as you have it done currently and put it back in the other machines you don't use under `sh_interpreter`. I'll take care of that.

2025-02-14 12:30 UTC, mandresm commented on src/esm_environment/esm_environment.py
> +            #)
```suggestion
```

2025-02-14 12:30 UTC, mandresm commented on src/esm_runscripts/oasis.py
> +            if mct_version >= (5,0):
```suggestion
            if mct_version >= (5, 0):
```

2025-02-14 12:30 UTC, mandresm commented on src/esm_runscripts/oasis.py
> +                self.namcouple += [" $NLOGPRT", "           " + str(debug_level) + " 0 1 ", " $END"]
```suggestion
                self.namcouple += [" $NLOGPRT", "           " + str(debug_level) + " 0 1", " $END"]
```

2025-02-14 12:30 UTC, mandresm commented on src/esm_runscripts/oasis.py
> +        if gconfig["run_number"] == 1 and config["lresume"] and gconfig["jobtype"] == "prepcompute" and config.get("norestart", "F") == "F":
```suggestion
        if (
            gconfig["run_number"] == 1
            and config["lresume"]
            and gconfig["jobtype"] == "prepcompute"
            and config.get("norestart", "F") == "F"
        ):
```

2025-02-14 16:50 UTC, mandresm commented on configs/components/oasis3mct/oasis3mct.yaml
> -mct_version: "2.8" # TODO: set mct_version = version (can't do at the moment as version is a string)
It was affecting but I pushed a commit to fix that. Now `mct_version: 2.8` is set in the setup files of `awicm-1` and `awiesm-2`.

2025-02-14 17:26 UTC, mandresm commented
Prior to merging "updating" this with `release` or merging this into `release` make sure to merge this #1299

2025-03-31 14:38 UTC, merged