Feat/awicm3 v3.3 and v3.4
esm-tools/esm_tools pull request #1251
Opened 2024-12-09 11:19 UTC by JanStreffing

Superseeds: https://github.com/esm-tools/esm_tools/pull/1193

2025-01-29 08:55 UTC, JanStreffing commented on namelists/fesom2/2.5/awicm3/v3.2/namelist.io
> +           'temp      ',1, 'm', 4,
This change is intentional. Needed for CMIPtool. I had too many bad runs with only yearly output.

2025-01-29 08:56 UTC, JanStreffing commented on namelists/fesom2/2.5/awicm3/v3.2/namelist.io
> +           'temp      ',1, 'm', 4,
Also only in fesom namelist template for AWI-CM3

2025-01-29 09:36 UTC, JanStreffing commented
Checks are giving errors like:

SUBMITTING (100.0%) awicm3/awicm3-v3.2-TCO95L91-CORE2_initial

Traceback (most recent call last):

```
git submodule init

git submodule update

  File "/opt/conda/envs/esm_tools/bin/esm_tests", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_tests')())
  File "/__w/esm_tools/esm_tools/src/esm_tests/cli.py", line 114, in main
    results = format_results(info)
  File "/__w/esm_tools/esm_tools/src/esm_tests/output.py", line 435, in format_results
    if not state["comp"]:
KeyError: 'comp'
Error: Process completed with exit code 1.
```

2025-02-14 11:07 UTC, JanStreffing commented on configs/machines/levante.yaml
> +            LD_LIBRARY_PATH[(0)]: /sw/spack-levante/intel-oneapi-mkl-2022.0.1-ttdktf/mkl/2022.0.1/lib/intel64:$LD_LIBRARY_PATH
Test if this is needed. It looks wrong to add LD_LIBRARY_PATH for intel compiler in system_gnu_libs block

2025-02-14 11:07 UTC, JanStreffing commented on configs/machines/levante.yaml
> +            IO_LIB_ROOT: "/work/ab0246/HPC_libraries/intel-oneapi-compilers/2022.0.1-gcc-11.2.0/openmpi/4.1.2-intel-2021.5.0"
Check if this is needed. Looks unused below.

2025-02-14 11:07 UTC, JanStreffing commented on configs/setups/awicm3/awicm3.yaml
>                          FESOM_USE_CPLNG: '"active"'
Check if still used anywhere. Else, remove.

2025-02-14 11:07 UTC, JanStreffing commented on namelists/oifs/48r1/xios/context_ifs.xml
> +      <variable id="nfrhis" name="NFRHIS" type="int"> 6 </variable>
Turn into jinja tempate and fill in from esm-tools

2025-02-14 11:10 UTC, pgierz requested changes
Small changes found while discussing the merge with @JanStreffing, see his comments. He will work on some last fixes.

This still needs the `further_reading` behaviour fixes as noted in #1285 and #1253 before it can reliably be used across various systems.

2025-02-14 11:12 UTC, JanStreffing commented
Todo add correct module list for 48r1 here

2025-02-20 17:31 UTC, JanStreffing commented
For OpenIFS 48r1 we need a python available, so that the preprocessor can do [fypp](https://fypp.readthedocs.io/en/stable/fypp.html). However, on levante, if I load the python3 module last, as I would happen when it comes from `oifs48.env.yaml` this overwrites any loaded netcdf module. Therefore python3 has to be loaded first, and the netcdf from python is then overwritten by the module load netcdf.

is there a feature for this alreadyß

2025-02-24 07:23 UTC, pgierz commented
I think the logic for the `[(#)]` applies to all export variables, so the LD_LIBRARY_PATH "should" fit that pattern as well. 

Do you have a reproducible counter example?

2025-05-09 09:32 UTC, mandresm requested changes
There are some minor changes, and I have some questions, but in general it's all pretty straight forward. I now need to look at the integration tests and see if there are any unexpected changes, but we are getting very close.

2025-05-09 09:32 UTC, mandresm commented on src/esm_runscripts/oasis.py
> +                self.namcouple += [" $NLOGPRT", "           " + "1", " $END"]
Just to confirm @JanStreffing, you want that here the debug level is always 1? It might be good to keep it as it was so that we can have control of it externally and that both versions behave the same. Does something speak against it?

2025-05-09 09:32 UTC, mandresm commented on configs/setups/oifsamip/oifsamip.yaml
> +                                - xios/xios.env.yaml
If `oifs`, `oasis` and `xios` yaml files load their own further reading (which I think they do), then you don't need this choose block here anymore.

2025-05-09 09:32 UTC, mandresm commented on configs/machines/levante.yaml
> +    compiler_mpi: gnu11_ompi4
I'm going to revert this change and leave `intel2022_openmpi` as default. With `v3.4` `gnu11` should be correctly selected now

2025-05-09 09:32 UTC, mandresm commented on configs/machines/levante.yaml
> +    #iolibraries: system_intel_impi_libs
Same as above

2025-05-09 09:32 UTC, mandresm commented on configs/machines/levante.yaml
> +    compiler_mpi: gnu11_ompi4
Confirmed, changing this does not affect to awicm3 3.3 or 3.4 envs.

2025-05-09 09:32 UTC, mandresm commented on configs/components/oasis3mct/oasis3mct.yaml
> +
If commented, can it then be removed?

```suggestion
```

2025-05-09 09:32 UTC, mandresm commented on configs/components/oifs/oifs43.env.yaml
Just to confirm that this is intentional. In this way `ECCODESROOT/lib` has less preference than the libs defined in `LD_LIBRARY_PATH`, right? Is this the intended behavior? If not you can reverted with the following suggestion.

```suggestion
            LD_LIBRARY_PATH[(3)]: "$ECCODESROOT/lib:$LD_LIBRARY_PATH"
```

2025-05-09 09:32 UTC, mandresm commented on configs/components/oifs/oifs43.cmip.yaml
> +oifs:
For every new file I will be passing now a yaml formater that indents to 4. I will leave non-new files untouch in this PR so that we can see the diffs clearly.

In the future the yaml formater will run in the CI and make sure that everything is formatted correctly.

2025-05-09 09:32 UTC, mandresm commented on configs/setups/awicm3/awicm3.yaml
> +            - fesom/fesom.env.yaml
This is not needed anymore. One can remove it safely because they are now loaded form the component and they are kept. I will take care of removing them in a commit soon.

2025-05-09 09:32 UTC, mandresm commented on configs/setups/awicm3/awicm3.yaml
> +                        # TODO: change this to a control on the patch version general.version
This needs to be dealt with.

2025-05-09 09:32 UTC, mandresm commented on configs/setups/awicm3/awicm3.yaml
> +                        mct_version: 6.0
Is this correct? Bumping up the mct_version of the `v3.2`?

2025-05-09 09:32 UTC, mandresm commented on configs/setups/awicm3/awicm3.yaml
> +        # TODO: change this to a control on the patch version general.version
Same as above, we have to discuss how we want to control this.

2025-05-09 09:32 UTC, mandresm commented on configs/setups/awicm3/awicm3.yaml
> +        choose_general.major_version:
I think there is some redundancy here with the oifs envs yamls. Now conflicts will be catch, but it might be worth it have it them in either one place or another.

2025-05-09 15:03 UTC, JanStreffing commented on src/esm_runscripts/oasis.py
> +                self.namcouple += [" $NLOGPRT", "           " + "1", " $END"]
I think this is fine.

2025-05-09 15:04 UTC, JanStreffing commented on configs/machines/levante.yaml
> +    compiler_mpi: gnu11_ompi4
correct, this was just the workaround from before you fixed things; back when the switches were not working.

2025-05-09 15:05 UTC, JanStreffing commented on configs/components/oasis3mct/oasis3mct.yaml
> +
Kinda? I guess we could dig it out again from the git history if we ever want to use oasis with yac interpolation again.

2025-05-09 15:06 UTC, JanStreffing commented on configs/components/oifs/oifs43.env.yaml
I forgot exactly why this was done. Especially for 43 it does not seem to make sense to me. I reverted back.

2025-05-09 15:07 UTC, JanStreffing commented on configs/components/oifs/oifs43.cmip.yaml
> +oifs:
great stuff!

2025-05-09 15:10 UTC, JanStreffing commented on configs/setups/awicm3/awicm3.yaml
> +                        # TODO: change this to a control on the patch version general.version
Meaning no more major_version? Everything is choose_version?

2025-05-09 15:12 UTC, JanStreffing commented on configs/setups/awicm3/awicm3.yaml
> +                        mct_version: 6.0
Yes, v3.2 was with oasis 6.0 and yac. in 3.2.2 i went back to 4.0.

2025-05-09 15:13 UTC, JanStreffing commented on configs/setups/awicm3/awicm3.yaml
> +                        mct_version: 6.0
But then again this never really worked. So it should not be used. too many people use v3.2 over 3.2.2. I will revert it.

2025-05-09 15:14 UTC, JanStreffing commented on configs/setups/awicm3/awicm3.yaml
> +                        mct_version: 6.0
i also deleted the line about using version 6.0-YAC above..

2025-05-09 15:14 UTC, JanStreffing commented on configs/setups/awicm3/awicm3.yaml
> +                        mct_version: 6.0
Perhaps should be tested with v3.2

2025-05-09 15:15 UTC, JanStreffing commented on configs/setups/awicm3/awicm3.yaml
> +        # TODO: change this to a control on the patch version general.version
lets have a chat next week.

2025-05-09 15:16 UTC, JanStreffing commented on configs/setups/awicm3/awicm3.yaml
> +        choose_general.major_version:
needs to be looked at? or do we wait until there are conflicts, if there are any?

2025-05-12 07:30 UTC, mandresm commented on configs/machines/levante.yaml
> +            - "load python3"
Let's be specific about the version, because otherwise the users will install on a python version, and then wonder why esm_runscripts is not running anymore their tidying job after python load in the .run.
```suggestion
            - "load python3/2023.01-gcc-11.2.0"
```

This should be fixed once we sort out the python environments into a smarter way, but for now we need to be careful with the python versions

2025-05-12 10:13 UTC, mandresm commented on configs/setups/awicm3/awicm3.yaml
> +                        mct_version: 6.0
I'll test v3.2

2025-05-12 10:14 UTC, mandresm commented on configs/components/oasis3mct/oasis3mct.yaml
> +
If this is something you might want to use in the future, then let's keep it.

2025-05-12 10:42 UTC, mandresm commented
None AWICM3 compilation seems to work in Juwels. It's probably a pretty simple fix, however, that would keep delaying this merge. @JanStreffing, should we treat this into a different issue/PR?

2025-05-12 11:08 UTC, mandresm commented
Including Python in the module loads seems to be breaking the linking of some older versions of FESOM. What is the reason behind including the module loading of Python @JanStreffing? Is it to be able to install oifs-48r1 with the bundle? If that's the case, would you be okay with me moving this into the `oifs-48r1.env.yaml`?

2025-05-12 11:18 UTC, JanStreffing commented
> None AWICM3 compilation seems to work in Juwels. It's probably a pretty simple fix, however, that would keep delaying this merge. @JanStreffing, should we treat this into a different issue/PR?

I'll spend half an hour looking into it.

2025-05-12 11:37 UTC, JanStreffing commented
> Including Python in the module loads seems to be breaking the linking of some older versions of FESOM. What is the reason behind including the module loading of Python @JanStreffing? Is it to be able to install oifs-48r1 with the bundle? If that's the case, would you be okay with me moving this into the `oifs-48r1.env.yaml`?

Yes, oifs48 need python at build time for some preprocessor bits. I don't think this will make a difference? It would still appear in fesom2 comp script in awicm3, no?

2025-05-12 11:48 UTC, mandresm commented
> > Including Python in the module loads seems to be breaking the linking of some older versions of FESOM. What is the reason behind including the module loading of Python @JanStreffing? Is it to be able to install oifs-48r1 with the bundle? If that's the case, would you be okay with me moving this into the `oifs-48r1.env.yaml`?
> 
> Yes, oifs48 need python at build time for some preprocessor bits. I don't think this will make a difference? It would still appear in fesom2 comp script in awicm3, no?

fesom-2.6 doesn't have a problem with that :)

2025-05-13 10:59 UTC, mandresm commented on configs/components/fesom/fesom-2.6.yaml
> +        branch: "2.6.8"
This is incorrect right?

```suggestion
      "2.6.9":
        branch: "2.6.9"
```

2025-05-13 11:30 UTC, JanStreffing commented on configs/components/fesom/fesom-2.6.yaml
> +        branch: "2.6.8"
oh yes!

2025-05-14 14:11 UTC, mandresm requested changes

2025-05-14 14:11 UTC, mandresm commented on configs/setups/awicm3/awicm3.yaml
> +                        # TODO: change this to a control on the patch version general.version
I mean:
```suggestion
                        choose_general.version:
                                "v3.3.0":
                                        version: awicm-3.1
                                "*":
                                        version: v1.1
```
This is to reduce the number of choose_resolution dependencies. At the moment version depends on -> general.major_version -> fesom.version which also depends on -> general.version.

In the way I am saying there is one choose less to be resolved in the backend: general.major_version -> general.version

2025-05-14 14:11 UTC, mandresm commented on configs/setups/awicm3/awicm3.yaml
> +                        # TODO: change this to a control on the patch version general.version
Do not commit this suggestion, I made one below equivalent to this one

2025-05-14 14:11 UTC, mandresm commented on configs/setups/awicm3/awicm3.yaml
> +                                        version: awicm-3.1
```suggestion
                        choose_general.version:
                                "v3.3.0":
                                        version: awicm-3.1
```

2025-05-14 14:22 UTC, mandresm commented on configs/setups/awicm3/awicm3.yaml
> +                        mct_version: 6.0
v3.2 works after this change. I am resolving this.

2025-05-14 14:58 UTC, mandresm commented on configs/setups/awicm3/awicm3.yaml
> +                "2.6.8":
```suggestion
        # This variable is only used for major versions of v3.3
        choose_general.version:
                "v3.3.0":
```

2025-05-14 19:27 UTC, mandresm commented
#bump

2025-05-14 19:29 UTC, mandresm approved these changes

2025-05-14 19:31 UTC, merged

2025-05-14 21:38 UTC, JanStreffing commented
:tada::tada::tada: