Awicm 3 frontiers xios
esm-tools/esm_tools pull request #353
Opened 2021-06-03 09:07 UTC by mandresm

Merging `xios` branch to the main branch.

2021-06-03 15:00 UTC, JanStreffing requested changes

2021-06-03 15:00 UTC, JanStreffing commented on configs/components/oifs/oifs.yaml
> +            #destination: oifs-43r3 TODO: JS: Had to comment this out. When I use destination the $model_dir changes, but $XIOS_TOPLEVEL is still pointing at oifs-43r3-awi-e1 leading to failed oasis
@mandresm Do you know why I had to do this?

2021-06-03 15:00 UTC, JanStreffing commented on configs/components/xios/xios.yaml
> +    archfile: ESMTOOLS_generic_oasis_cray # TODO: fix and use choose block above
I think this needs to be worked on, because it's hardcoded for cray maschines at the moment.

2021-06-03 15:00 UTC, JanStreffing commented on configs/components/xios/xios.yaml
> +
This seems like a strange addition for the XIOS merge, since I did most of my work on XIOS on Aleph. I did first compile XIOS, without integrating it into OpenIFS on Ollie. So maybe this was needed?

2021-06-03 15:00 UTC, JanStreffing commented on runscripts/awicm3/awicm3-aleph-TL159L60-CORE2.yaml
> +    heterogeneous_parallelization: true
May need a sanity check, if this is the right name for the option in the target branch.

2021-06-03 15:28 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +            #destination: oifs-43r3 TODO: JS: Had to comment this out. When I use destination the $model_dir changes, but $XIOS_TOPLEVEL is still pointing at oifs-43r3-awi-e1 leading to failed oasis
Nope, I'll have a look at that before merging.

2021-06-04 09:39 UTC, mandresm commented on configs/components/xios/xios.yaml
> +
Probably this was needed, but this won't go into the environment of AWICM3 as we decided to go there with an environment that we specifically ignores environments in the components and only takes the environments specified in awicm3.yaml. 

We could change that of course by either not ignoring component environments, or (the easiest solution) getting all the environment from `xios.yaml` and put them into an `xios.env.yaml` and then loading it with a `further_reading` in `awicm3.yaml`.

2021-06-04 09:40 UTC, mandresm commented on runscripts/awicm3/awicm3-aleph-TL159L60-CORE2.yaml
> +    heterogeneous_parallelization: true
No it's not, it needs to go on computer. I'll take care of that. Should the value be true?

2021-06-04 10:03 UTC, JanStreffing commented on configs/components/xios/xios.yaml
> +
I think the second solution might be easier for now (moving this to `awicm3.env.yaml`). I suspect XIOS will not be used by any other models on ollie.

2021-06-04 10:04 UTC, JanStreffing commented on runscripts/awicm3/awicm3-aleph-TL159L60-CORE2.yaml
> +    heterogeneous_parallelization: true
Yeah I think true a good default for aleph. We know it works well on PBS.

2021-06-04 10:06 UTC, JanStreffing commented on configs/components/oifs/oifs.yaml
> +            #destination: oifs-43r3 TODO: JS: Had to comment this out. When I use destination the $model_dir changes, but $XIOS_TOPLEVEL is still pointing at oifs-43r3-awi-e1 leading to failed oasis
So I can recall that this had something to do with the name of the folder that the component was installed into not matching with where it was looking for it elsewhere. But I forgot what that elsewhere was..

2021-06-08 07:36 UTC, mandresm commented on configs/components/oifs/oifs.yaml
> +            #destination: oifs-43r3 TODO: JS: Had to comment this out. When I use destination the $model_dir changes, but $XIOS_TOPLEVEL is still pointing at oifs-43r3-awi-e1 leading to failed oasis
Jan, this is not for the branch we typically use for AWICM3 (for that we use `oifs-43r3-awi-frontiers`, this one is `43r3-awi-e1`). Is this just for standalone `OpenIFS` with `xios`?

2021-06-08 08:35 UTC, JanStreffing commented on configs/components/oifs/oifs.yaml
> +            #destination: oifs-43r3 TODO: JS: Had to comment this out. When I use destination the $model_dir changes, but $XIOS_TOPLEVEL is still pointing at oifs-43r3-awi-e1 leading to failed oasis
I think so, yes. It was part of the first commit where I was testing installing XIOS on ollie.

2021-06-08 11:57 UTC, merged